# Generated by Django 3.0.3 on 2020-04-10 17:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FundingResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('due_date', models.DateField()),
                ('source_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('url', models.URLField(help_text='Be sure to include the full url, i.e. start with http://')),
                ('agenda', models.FileField(blank=True, null=True, upload_to='')),
                ('minutes', models.FileField(blank=True, null=True, upload_to='')),
                ('minutes_added', models.DateField(blank=True, null=True)),
                ('presentation_materials', models.FileField(blank=True, upload_to='')),
                ('pre_mat_added', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the page.', max_length=30)),
                ('main_content', ckeditor.fields.RichTextField(help_text='Main content (left column).')),
                ('sidebar', ckeditor.fields.RichTextField(blank=True, help_text='Sidebar/additional info (right column). If empty, there is default text that  will be displayed.', null=True)),
                ('internal_name', models.CharField(help_text='Only editable by superuser; used to select appropriate page for views/templates.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('summary', models.TextField()),
                ('publication_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('regional_plans', 'Regional Plans'), ('municipal_tools', 'Municipal Tools'), ('research_and_reports', 'Research and Reports')], max_length=30)),
                ('pdf', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
