# Generated by Django 3.0.3 on 2020-02-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='minutes',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='presentation_materials',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
