# Generated by Django 3.0.3 on 2020-04-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(help_text='24 hr format, i.e. 09:00 for 9am or 13:00 for 1pm'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.URLField(blank=True, help_text='To the Ticketleap page. Include the full url, i.e. start with http://', null=True),
        ),
    ]
