# Generated by Django 3.0.3 on 2020-04-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200422_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(help_text='Date in format mm/dd/yyyy or mm/dd/yy  and time in 24 hr format, i.e. 09:00 for 9am or 13:00 for 1pm'),
        ),
    ]
