# Generated by Django 3.0.3 on 2020-02-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200213_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('left_column', models.TextField()),
                ('right_column', models.TextField()),
            ],
        ),
    ]
