# Generated by Django 3.0.3 on 2020-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200424_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingresource',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fundingresource',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technicalresource',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
