# Generated by Django 3.0.3 on 2020-02-14 14:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200213_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='left_column',
        ),
        migrations.RemoveField(
            model_name='page',
            name='right_column',
        ),
        migrations.AddField(
            model_name='page',
            name='main_content',
            field=ckeditor.fields.RichTextField(default='main content', help_text='Main content (left column).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='sidebar',
            field=ckeditor.fields.RichTextField(default='sidebar', help_text='Sidebar/additional info (right column).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='agenda',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
