# Generated by Django 3.0.3 on 2020-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200424_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingresource',
            old_name='summary',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='technicalresource',
            name='url',
            field=models.URLField(help_text='Include http://'),
        ),
    ]
