# Generated by Django 3.0.3 on 2020-04-30 21:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200424_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingresource',
            name='url',
            field=models.URLField(help_text='Include http://'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sidebar',
            field=ckeditor.fields.RichTextField(default='test', help_text='Sidebar/additional info (right column). If empty, there is default text that  will be displayed.'),
            preserve_default=False,
        ),
    ]
