# Generated by Django 3.0.3 on 2020-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200214_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RP', 'Regional Plans'), ('MT', 'Municipal Tools'), ('RR', 'Research and Reports')], max_length=2)),
            ],
        ),
    ]
