# Generated by Django 3.0.3 on 2020-04-30 21:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200430_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='sidebar',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Sidebar/additional info (right column).', null=True),
        ),
    ]
