# Generated by Django 3.0.3 on 2020-06-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200430_1705'),
        ('web', '0006_auto_20200430_1715'),
    ]

    operations = [
    ]
