# Generated by Django 3.0.3 on 2020-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200430_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingresource',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
