# Generated by Django 3.0.3 on 2020-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_fundingresources_technicalresources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingresources',
            old_name='date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='fundingresources',
            name='source',
        ),
        migrations.AddField(
            model_name='fundingresources',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='technicalresources',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='technicalresources',
            name='summary',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
