# Generated by Django 3.0.3 on 2020-06-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200611_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalresource',
            name='url',
            field=models.URLField(blank=True, help_text='Include http://', null=True),
        ),
    ]
