# Generated by Django 3.0.3 on 2020-06-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_merge_20200611_0737'),
        ('web', '0008_auto_20200611_0759'),
    ]

    operations = [
    ]
