# Generated by Django 3.0.3 on 2020-02-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200219_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundingResources',
            new_name='FundingResource',
        ),
        migrations.RenameModel(
            old_name='TechnicalResources',
            new_name='TechnicalResource',
        ),
    ]
