# Generated by Django 3.0.3 on 2020-06-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200611_0832'),
        ('web', '0009_merge_20200611_0818'),
    ]

    operations = [
    ]
