# Generated by Django 3.0.3 on 2020-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_merge_20200611_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalresource',
            name='url',
            field=models.URLField(blank=True, help_text='Be sure to include http:// or https://', null=True),
        ),
    ]
