# Generated by Django 3.0.3 on 2020-02-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200219_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingresource',
            old_name='source_url',
            new_name='url',
        ),
    ]
