# Generated by Django 3.0.3 on 2020-02-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200219_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalresource',
            old_name='date',
            new_name='publication_date',
        ),
    ]
