# Generated by Django 3.0.3 on 2020-02-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200219_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalresource',
            name='url',
            field=models.URLField(default='http://www.dvrpc.org'),
            preserve_default=False,
        ),
    ]
