# Generated by Django 3.0.3 on 2020-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200618_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Date in format m/d/yyyy, m/d/yy, yy-m-d, or yyyy-m-d  and time in 24 hr format, i.e. 09:00 for 9am or 13:00 for 1pm'),
        ),
    ]
