# Generated by Django 2.2.10 on 2020-02-20 18:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_technicalresource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='sidebar',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Sidebar/additional info (right column).', null=True),
        ),
    ]
