# Generated by Django 3.0.3 on 2020-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200618_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fundingresource',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.URLField(blank=True, help_text='To the Ticketleap page.', null=True),
        ),
        migrations.AlterField(
            model_name='technicalresource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
