# Generated by Django 3.0.3 on 2020-06-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200625_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='presentation_materials',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
